on: [push]

jobs:
  docsearch_job:
    runs-on: ubuntu-latest
    name: Crawl docsearch
    steps:
      - run: echo "Hello"
      - uses: samajammin/docsearch-crawl@v0.0.1
      - run: echo "Goodbye"
